"""Document upload into the KB — PDF/markdown loading, and which files a run picks up.

The Qdrant round-trip is covered by the vector-RAG tests; what is pinned here is everything that
decides whether an uploaded protocol becomes *findable*: PDF text surviving extraction with its page
citation intact, hard-wrapped lines being rebuilt without shredding a checklist, and unreadable
files failing with a diagnosis instead of being indexed as empty.

The PDF fixture is generated byte-by-byte rather than committed or produced with a writer
dependency, so the test exercises the real pypdf path with known-good input.
"""

from __future__ import annotations

import pytest

from cli.kb_upload import check_embedder_matches_store, keep_copy, resolve_files
from cli.kb_vector import _managed_uploads
from kb.vector.chunking import chunk_document
from kb.vector.loader import dewrap, pages_to_markdown, read_document


def make_pdf(pages: list[list[str]]) -> bytes:
    """A minimal, valid, text-bearing PDF — one Helvetica text object per page."""
    objs, page_ids, n = [], [], len(pages)
    font_id = 3 + 2 * n
    for i, lines in enumerate(pages):
        pid, cid = 3 + 2 * i, 4 + 2 * i
        page_ids.append(pid)
        body = "BT /F1 12 Tf 72 720 Td 14 TL\n" + "".join(
            f"({ln.replace('(', '').replace(')', '')}) Tj T*\n" for ln in lines) + "ET"
        objs.append((pid, f"<</Type/Page/Parent 2 0 R/MediaBox[0 0 612 792]"
                          f"/Contents {cid} 0 R/Resources<</Font<</F1 {font_id} 0 R>>>>>>"))
        objs.append((cid, f"<</Length {len(body)}>>\nstream\n{body}\nendstream"))
    objs.append((font_id, "<</Type/Font/Subtype/Type1/BaseFont/Helvetica>>"))
    objs.insert(0, (2, f"<</Type/Pages/Kids[{' '.join(f'{p} 0 R' for p in page_ids)}]/Count {n}>>"))
    objs.insert(0, (1, "<</Type/Catalog/Pages 2 0 R>>"))
    out, offsets = bytearray(b"%PDF-1.4\n"), {}
    for num, payload in sorted(objs):
        offsets[num] = len(out)
        out += f"{num} 0 obj {payload} endobj\n".encode("latin-1")
    xref, top = len(out), max(offsets) + 1
    out += f"xref\n0 {top}\n0000000000 65535 f \n".encode()
    for i in range(1, top):
        out += f"{offsets.get(i, 0):010d} 00000 n \n".encode()
    out += f"trailer <</Size {top}/Root 1 0 R>>\nstartxref\n{xref}\n%%EOF\n".encode()
    return bytes(out)


# --- rebuilding PDF text ------------------------------------------------------------------------

def test_wrapped_prose_is_rejoined():
    # PDF extraction breaks lines at the layout width; left alone, an embedding sees fragments.
    assert dewrap("The patient should be\nassessed for stability.") == \
        "The patient should be assessed for stability."


def test_a_word_split_across_lines_loses_its_hyphen():
    assert dewrap("assess haemo-\ndynamic stability") == "assess haemodynamic stability"


def test_checklist_items_are_never_merged():
    # The case that makes the naive "join every line" approach wrong: numbered steps end at a
    # sentence boundary, and merging them buries each step inside its neighbours.
    out = dewrap("1. Confirm rhythm.\n2. Assess stability.\n3. Rate control.")
    assert out.split("\n\n") == ["1. Confirm rhythm.", "2. Assess stability.", "3. Rate control."]


def test_pages_keep_their_printed_number_when_one_is_blank():
    # Page 2 extracts to nothing (an image); page 3 must still be cited as page 3, or the citation
    # sends the clinician to the wrong page.
    md = pages_to_markdown(["first", "", "third"])
    assert "## page 1" in md and "## page 3" in md and "## page 2" not in md


# --- reading real files -------------------------------------------------------------------------

def test_pdf_chunks_carry_a_page_citation(tmp_path):
    pytest.importorskip("pypdf")
    path = tmp_path / "af_sop.pdf"
    path.write_bytes(make_pdf([["Atrial Fibrillation SOP", "1. Confirm rhythm on a 12-lead ECG."],
                               ["Escalation checklist", "Call cardiology above 150 bpm."]]))
    chunks = chunk_document(read_document(path), path.name)
    assert [c.source for c in chunks] == ["af_sop.pdf#page 1", "af_sop.pdf#page 2"]
    assert "12-lead ECG" in chunks[0].text and "cardiology" in chunks[1].text


def test_scanned_pdf_is_refused_with_the_reason(tmp_path):
    pytest.importorskip("pypdf")
    path = tmp_path / "scan.pdf"
    path.write_bytes(make_pdf([[], []]))  # pages with no text objects = a scan, as far as we can tell
    with pytest.raises(ValueError, match="no extractable text"):
        read_document(path)


def test_markdown_is_not_reflowed(tmp_path):
    # Markdown is already the chunker's input format; de-wrapping it would destroy the headings the
    # citations are built from.
    path = tmp_path / "sop.md"
    path.write_text("# Rate control\n\nGive a beta-blocker.\n", encoding="utf-8")
    assert read_document(path) == "# Rate control\n\nGive a beta-blocker.\n"


def test_unsupported_and_missing_and_empty_are_distinguishable(tmp_path):
    (tmp_path / "notes.docx").write_text("x", encoding="utf-8")
    (tmp_path / "blank.md").write_text("   \n", encoding="utf-8")
    with pytest.raises(ValueError, match="unsupported type"):
        read_document(tmp_path / "notes.docx")
    with pytest.raises(FileNotFoundError):
        read_document(tmp_path / "nope.md")
    with pytest.raises(ValueError, match="empty"):
        read_document(tmp_path / "blank.md")


# --- what a run picks up ------------------------------------------------------------------------

def test_directory_upload_ignores_unsupported_files(tmp_path):
    for name in ("a.pdf", "b.md", "roster.xlsx", "notes.txt"):
        (tmp_path / name).write_text("x", encoding="utf-8")
    picked = {p.name for p in resolve_files([], str(tmp_path), "*")}
    assert picked == {"a.pdf", "b.md", "notes.txt"}  # a folder of protocols also holds spreadsheets


def test_a_file_named_twice_uploads_once(tmp_path):
    (tmp_path / "a.md").write_text("x", encoding="utf-8")
    picked = resolve_files([str(tmp_path / "a.md")], str(tmp_path), "*")
    assert len(picked) == 1


def test_explicitly_named_unsupported_file_is_kept_so_it_can_be_explained(tmp_path):
    # Silently dropping it would leave the user staring at "nothing to upload".
    path = tmp_path / "notes.docx"
    path.write_text("x", encoding="utf-8")
    assert resolve_files([str(path)], None, "*") == [path]


# --- the trap this feature would otherwise walk into ---------------------------------------------

class _Store:
    collection = "rmsai_docs"

    def __init__(self, dim):
        self._dim = dim

    def vector_dim(self):
        return self._dim


def test_uploading_with_the_wrong_embedder_is_refused():
    # 384-dim BGE vectors into a 256-dim hashing collection: an opaque client error at best, and
    # silently unusable search at worst. The dimension is the only fingerprint of which embedder
    # built a collection.
    problem = check_embedder_matches_store(_Store(256), 384)
    assert problem and "256" in problem and "384" in problem and "--reset" in problem
    assert check_embedder_matches_store(_Store(384), 384) is None
    assert check_embedder_matches_store(_Store(None), 384) is None  # empty collection: anything goes


# --- the managed folder: surviving a corpus rebuild ----------------------------------------------

def test_upload_is_kept_so_a_rebuild_can_find_it_again(tmp_path):
    # Uploads exist only as vectors, and `kb_vector index --reset` recreates the collection from
    # disk. Without a kept source, a rebuild silently deletes every uploaded protocol.
    src, managed = tmp_path / "in" / "af.md", tmp_path / "managed"
    src.parent.mkdir()
    src.write_text("# AF SOP\n\nRate control first.\n", encoding="utf-8")
    kept = keep_copy(src, managed)
    assert kept == managed / "af.md" and kept.read_text() == src.read_text()


def test_reuploading_an_edited_document_replaces_the_kept_copy(tmp_path):
    src, managed = tmp_path / "af.md", tmp_path / "managed"
    src.write_text("v1", encoding="utf-8")
    keep_copy(src, managed)
    src.write_text("v2 — now with cardioversion", encoding="utf-8")
    assert keep_copy(src, managed).read_text() == "v2 — now with cardioversion"


def test_uploading_a_file_already_in_the_folder_is_not_self_destructive(tmp_path):
    # Re-running an upload against the managed folder itself must not copy a file onto itself.
    managed = tmp_path / "managed"
    managed.mkdir()
    inside = managed / "af.md"
    inside.write_text("keep me", encoding="utf-8")
    assert keep_copy(inside, managed).read_text() == "keep me"


def test_rebuild_only_picks_up_supported_documents(tmp_path):
    for name in ("a.pdf", "b.md", "notes.txt", "roster.xlsx", ".DS_Store"):
        (tmp_path / name).write_text("x", encoding="utf-8")
    (tmp_path / "subdir").mkdir()
    assert {p.name for p in _managed_uploads(str(tmp_path))} == {"a.pdf", "b.md", "notes.txt"}


def test_rebuild_without_an_upload_folder_is_a_no_op(tmp_path):
    assert _managed_uploads(str(tmp_path / "nope")) == []
    assert _managed_uploads("") == []   # explicitly disabled
    assert _managed_uploads(None) == []
